# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Victor Young"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Gems
plugins:
  - jekyll-gist

# Navigation
nav:
  - name:           "关于"
    href:           "/about.html"
  - name:           "主题下载"
    href:           "https://github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# 百度统计
# baidu_analyze: 6cbd58856f0a045b48fc948c2e4679c6

utterance:
  # Note: Make sure the repo is public, otherwise your readers will not be able to view the issues/comments.
  # Make sure the [utterances app](https://github.com/apps/utterances) is installed on the repo, otherwise users will not be able to post comments.
  #  If your repo is a fork, navigate to it's settings tab and confirm the issues feature is turned on.
  repo: Youngv/rt4u.bid # Choose the repository utterances will connect to. eg: owner/repo
  issue-term: title   # Choose the mapping between blog posts and GitHub issues. 
  theme: github-light # Choose an Utterances theme that matches your blog. 'github-light' is default

  ## Optional
  label:  blog-comments # Choose the label that will be assigned to issues created by Utterances.
